# Basic `dependabot.yml` to check GH actions and Docker
# see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "github-actions"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/workers/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

