apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: htcondor-cm-connectivity
spec:
  podSelector:
    matchLabels:
      app: "htcondor-cm"
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 9618
    - protocol: TCP
      port: 51450
    - protocol: TCP
      port: 41450
  egress:
  - {}
