apiVersion: v1
kind: PersistentVolume
metadata:
  name: condor-passwd-pv
spec:
  storageClassName: local-storage
  local:
    path: {{ .Values.condorCredsMountRoot }}/passwords.d
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.hostHostname }}
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: condor-passwd-pvc
spec:
  storageClassName: local-storage
  volumeName: condor-passwd-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: condor-tokens-pv
spec:
  storageClassName: local-storage
  local:
    path: {{ .Values.condorCredsMountRoot }}/tokens.d
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.hostHostname }}
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: condor-tokens-pvc
spec:
  storageClassName: local-storage
  volumeName: condor-tokens-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-passwd-pv
spec:
  storageClassName: local-storage
  local:
    path: {{ .Values.frontendCredsMountRoot }}/passwords.d
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.hostHostname }}
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-passwd-pvc
spec:
  storageClassName: local-storage
  volumeName: frontend-passwd-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-tokens-pv
spec:
  storageClassName: local-storage
  local:
    path: {{ .Values.frontendCredsMountRoot }}/tokens.d
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.hostHostname }}
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-tokens-pvc
spec:
  storageClassName: local-storage
  volumeName: frontend-tokens-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
