# SPDX-FileCopyrightText: 2020 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

# IMAGE_NAMESPACE: 'glideinwms'
# GWMS_PATH: 'gwms-dev-local'

services:

  ce-workspace:
    container_name: ce-workspace.glideinwms.org
    build:
      context: .
      cache_from:
        - ${IMAGE_NAMESPACE-glideinwms}/ce-workspace:latest
      dockerfile: ce-workspace/Dockerfile
    image: ${IMAGE_NAMESPACE-glideinwms}/ce-workspace:latest
    networks:
      - gwms
    hostname: ce-workspace.glideinwms.org
    tty: true
    stdin_open: true
    stop_grace_period: 2s

  factory-workspace:
    container_name: factory-workspace.glideinwms.org
    build:
      context: .
      cache_from:
        - ${IMAGE_NAMESPACE-glideinwms}/factory-workspace:latest
      dockerfile: factory-workspace/Dockerfile
    image: ${IMAGE_NAMESPACE-glideinwms}/factory-workspace:latest
    volumes:
      - gwms-tokens:/var/lib/gwms-factory/.condor/tokens.d
      - ${GWMS_PATH-gwms-dev-local}:/opt/gwms
    networks:
      - gwms
    hostname: factory-workspace.glideinwms.org
    depends_on:
      - ce-workspace
    tty: true
    stdin_open: true
    stop_grace_period: 2s

  frontend-workspace:
    container_name: frontend-workspace.glideinwms.org
    build:
      context: .
      cache_from:
        - ${IMAGE_NAMESPACE-glideinwms}/frontend-workspace:latest
      dockerfile: frontend-workspace/Dockerfile
    image: ${IMAGE_NAMESPACE-glideinwms}/frontend-workspace:latest
    volumes:
      - gwms-tokens:/var/lib/gwms-frontend/.condor/tokens.d
      - ${GWMS_PATH-gwms-dev-local}:/opt/gwms
    networks:
      - gwms
    hostname: frontend-workspace.glideinwms.org
    depends_on:
      - factory-workspace
    tty: true
    stdin_open: true
    stop_grace_period: 2s

volumes:
  gwms-dev-local:
    driver: local
  gwms-tokens:
    driver: local

networks:
  gwms:
    driver: bridge
