apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vo-frontend-connectivity
spec:
  podSelector:
    matchLabels:
      app: "vo-frontend"
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 80
  egress:
  - {}